force-app/main/default/objects/ActivityHistory__c/ActivityHistory__c.object-meta.xml
<CustomObject>
    <label>ActivityHistory</label>
    <nameField>
        <displayFormat>AH-{0}</displayFormat>
        <label>ActivityHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActivityHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityHistory__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>NewValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>OldValue</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityHistory__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User Who Changed</inlineHelpText>
    <label>Who</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ActivityHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HistoryController.cls
public with sharing class HistoryController {

    @AuraEnabled
    public static String getHistoryForRecord(String recordId) {
        List<ActivityHistory__c> history = [SELECT FieldName__c,
                                                   OldValue__c,
                                                   NewValue__c,
                                                   Who__c,
                                                   CreatedDate
                                                FROM ActivityHistory__c
                                                WHERE SObjectId__c = :recordId
                                                ORDER BY CreatedDate DESC];
        
        Set<Id> usersIds = new Set<Id>();
        for (ActivityHistory__c ah : history) {
            usersIds.add(ah.Who__c);
        }

        Map<Id, User> usersMap = new Map<Id, User>([SELECT Name FROM User WHERE Id IN :usersIds]);

        Integer position = 1;                                                
        List<ResponseWrapper> responseWrapper = new List<ResponseWrapper>();
        for (ActivityHistory__c h : history) {

            ResponseWrapper rwTemp = new ResponseWrapper(
                position++, 
                h.FieldName__c,
                String.valueOf(h.OldValue__c), 
                String.valueOf(h.NewValue__c), 
                usersMap.get(h.Who__c).Name,
                String.valueOf(h.CreatedDate)
            );

            responseWrapper.add(rwTemp);
        }
        
        return JSON.serialize(responseWrapper);
    }

    public class ResponseWrapper {
        public Integer position;
        public String fieldName;
        public String oldValue;
        public String newValue;
        public String who;
        public String createdDate;

        public ResponseWrapper(Integer position, String fieldName, String oldValue, String newValue, String who, String createdDate) {
            this.position = position;
            this.fieldName = fieldName;
            this.oldValue = oldValue;
            this.newValue = newValue;
            this.who = who;
            this.createdDate = createdDate;
        }
    }
}